# Generated by Django 3.0.6 on 2020-05-08 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('perishable', models.BooleanField(default=False)),
                ('manufacture_date', models.DateField()),
                ('shelf_life', models.DateField(null=True)),
            ],
        ),
    ]
