# Generated by Django 3.0.6 on 2020-05-08 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='shelf_life',
            new_name='expiry_date',
        ),
    ]
