# Generated by Django 3.0.6 on 2020-05-10 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20200510_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='rating',
        ),
    ]
