# Generated by Django 3.0.6 on 2020-05-14 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
    ]
